#
# Makefile
# Copyright (c) 2022-2023 Jarosław Stańczyk <jaroslaw@stanczyk.pro>
#
TOOLS := ../make
include $(TOOLS)/make1b.mk
include $(TOOLS)/make_c1.mk

.PHONY: all
all: prg43-01 prg43-02 prg43-03

prg43-01: prg43-01.c
prg43-02: prg43-02.c
prg43-03: prg43-03.c

include $(TOOLS)/make_c2.mk
include $(TOOLS)/make_clean.mk
# eof.