#
# Makefile
# Copyright (c) 2022-2024 Jarosław Stańczyk <jaroslaw@stanczyk.pro>
#
TOOLS := ../make
include $(TOOLS)/make1b.mk
include $(TOOLS)/make_c1.mk

.PHONY: all
all: prg22-01 prg22-02 prg22-03 prg22-04
prg22-01: prg22-01.c
prg22-02: prg22-02.c
prg22-03: prg22-03.c
prg22-04: prg22-04.c

include $(TOOLS)/make_c2.mk
include $(TOOLS)/make_clean.mk
# eof.