#
# Makefile
# Copyright (c) 2022-2023 Jarosław Stańczyk <jaroslaw@stanczyk.pro>
#
TOOLS := ../make
include $(TOOLS)/make1b.mk
include $(TOOLS)/make_c1.mk

.PHONY: all
all: 	prg40-00 \
		prg40-01 prg40-02 prg40-03 prg40-04 prg40-05 prg40-06 prg40-07 prg40-08

prg40-00: prg40-00.c
prg40-01: prg40-01.c
prg40-02: prg40-02.c
prg40-03: prg40-03.c
prg40-04: prg40-04.c
prg40-05: prg40-05.c
prg40-06: prg40-06.c
prg40-07: prg40-07.c
prg40-08: prg40-08.c

include $(TOOLS)/make_c2.mk
include $(TOOLS)/make_clean.mk
# eof.