#
# Makefile
# Copyright (c) 2022-2024 Jarosław Stańczyk <jaroslaw@stanczyk.pro>
#
TOOLS := ../make
include $(TOOLS)/make1b.mk
include $(TOOLS)/make_c1.mk

.PHONY: all
all: prg09-01 prg09-02 prg09-03 prg09-04 prg09-05 prg09-06 prg09-07 prg09-08 prg09-09 prg09-10 \
	 prg09-11
prg09-01: prg09-01.c
prg09-02: prg09-02.c
prg09-03: prg09-03.c
prg09-04: prg09-04.c
prg09-05: prg09-05.c
prg09-06: prg09-06.c
prg09-07: prg09-07.c
prg09-08: prg09-08.c
prg09-09: prg09-09.c
prg09-10: prg09-10.c
prg09-11: prg09-11.c

include $(TOOLS)/make_c2.mk
include $(TOOLS)/make_clean.mk
# eof.