#
# Makefile
# Copyright (c) 2022-2024 Jarosław Stańczyk <jaroslaw@stanczyk.pro>
#
TOOLS := ../make
include $(TOOLS)/make1b.mk
include $(TOOLS)/make_c1.mk

.PHONY: all
all: prg27-00 prg27-01
prg27-00: prg27-00.c
prg27-01: prg27-01.c

include $(TOOLS)/make_c2.mk
include $(TOOLS)/make_clean.mk
# eof.