#
# Makefile
# Copyright (c) 2022-2023 Jarosław Stańczyk <jaroslaw@stanczyk.pro>
#
TOOLS := ../make
include $(TOOLS)/make1b.mk
include $(TOOLS)/make_c1.mk

.PHONY: all
all: prg07-01 prg07-02 prg07-03 prg07-04 prg07-05 prg07-06 prg07-07 prg07-08 prg07-09

prg07-01: prg07-01.c
prg07-02: prg07-02.c
prg07-03: prg07-03.c
prg07-04: prg07-04.c
prg07-05: prg07-05.c
prg07-06: prg07-06.c
prg07-07: prg07-07.c
prg07-08: prg07-08.c
prg07-09: prg07-09.c

include $(TOOLS)/make_c2.mk
include $(TOOLS)/make_clean.mk
# eof.